In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm,datasets
from sklearn.svm import  SVC
import numpy as np
from sklearn.metrics import accuracy_score

df = pd.read_csv('aftercleaning.csv')
df.info()

#143745 - mean
#classification - by using the mean
a = df['Reported number of people receiving ART'].mean()
df['label']=np.where(df['Reported number of people receiving ART']>a,'good','bad')
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 11 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Country                                                         138 non-null    object
 1   Reported number of people receiving ART                         138 non-null    int64
 2   Estimated number of people living with HIV                      136 non-null    object
 3   Estimated ART coverage among people living with HIV (%)         136 non-null    object
 4   Estimated number of people living with HIV_median               138 non-null    float64
 5   Estimated number of people living with HIV_min                  138 non-null    float64
 6   Estimated number of people living with HIV_max                  138 non-null    float64
 7   Estimated ART coverage among people living with HIV (%)_median  136 non-null    float64
 8   Estimated ART coverage among people living with HIV (%)_min     136 non-null    float64
 9   Estimated ART coverage among people living with HIV (%)_max     136 non-null    float64
 10  WHO Region                                                      136 non-null    object
dtypes: float64(6), int64(1), object(4)
memory usage: 12.0+ KB

,Country,Reported number of people receiving ART,Estimated number of people living with HIV,Estimated ART coverage among people living with HIV (%),Estimated number of people living with HIV_median,Estimated number of people living with HIV_min,Estimated number of people living with HIV_max,Estimated ART coverage among people living with HIV (%)_median,Estimated ART coverage among people living with HIV (%)_min,Estimated ART coverage among people living with HIV (%)_max,WHO Region,label
0,Afghanistan,920,7200[4100–11000],13[7–20],7200.0,4100.0,11000.0,13.0,7.0,20.0,Eastern Mediterranean,bad
1,Algeria,12800,16000[15000–17000],81[75–86],16000.0,15000.0,17000.0,81.0,75.0,86.0,Africa,bad
2,Angola,88700,330000[290000–390000],27[23–31],330000.0,290000.0,390000.0,27.0,23.0,31.0,Africa,bad
3,Argentina,85500,140000[130000–150000],61[55–67],140000.0,130000.0,150000.0,61.0,55.0,67.0,Americas,bad
4,Armenia,1900,3500[3000–4400],53[44–65],3500.0,3000.0,4400.0,53.0,44.0,65.0,Europe,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
133,Yemen,2200,11000[6500–18000],21[12–35],11000.0,6500.0,18000.0,21.0,12.0,35.0,Eastern Mediterranean,bad
134,Zambia,965000,1200000[1100000–1400000],78[69–88],1200000.0,1100000.0,1400000.0,78.0,69.0,88.0,Africa,good
135,Zimbabwe,1151000,1300000[1100000–1500000],88[77–95],1300000.0,1100000.0,1500000.0,88.0,77.0,95.0,Africa,good
136,MIN_VAL,100,NaN,NaN,200.0,100.0,500.0,NaN,NaN,NaN,NaN,bad
137,MAX_VAL,9900,NaN,NaN,7700000.0,7100000.0,8300000.0,NaN,NaN,NaN,NaN,bad

In [17]:
#cutting the data only up to 100
X=df.iloc[0:76,[1,4,7,9]]
print(X)
y=df.loc[0:75,'label']
print(y)

    Reported number of people receiving ART  \
0                                       920
1                                     12800
2                                     88700
3                                     85500
4                                      1900
..                                      ...
71                                     3700
72                                     6500
73                                     2400
74                                     1500
75                                   206000

    Estimated number of people living with HIV_median  \
0                                              7200.0
1                                             16000.0
2                                            330000.0
3                                            140000.0
4                                              3500.0
..                                                ...
71                                             8500.0
72                                            12000.0
73                                             5300.0
74                                             2500.0
75                                           340000.0

    Estimated ART coverage among people living with HIV (%)_median  \
0                                                13.0
1                                                81.0
2                                                27.0
3                                                61.0
4                                                53.0
..                                                ...
71                                               43.0
72                                               54.0
73                                               45.0
74                                               60.0
75                                               61.0

    Estimated ART coverage among people living with HIV (%)_max
0                                                20.0
1                                                86.0
2                                                31.0
3                                                67.0
4                                                65.0
..                                                ...
71                                               59.0
72                                               62.0
73                                               50.0
74                                               67.0
75                                               65.0

[76 rows x 4 columns]
0      bad
1      bad
2      bad
3      bad
4      bad
      ...
71     bad
72     bad
73     bad
74     bad
75    good
Name: label, Length: 76, dtype: object

In [31]:
#if c is inreased more accurate; c=1 accuracy 1
clf = svm.SVC(kernel='rbf', random_state=1, gamma=1, C=1)

#train the model
clf.fit(X, y)

#just use the same data to predict for now
y_pred=clf.predict(X)


print(accuracy_score(y, y_pred))

1.0